# MATLAB Compiler Runtime (MCR) v9.11 (R2021b)
#
# This docker file will configure an environment into which the Matlab compiler
# runtime will be installed and in which stand-alone matlab routines (such as
# those created with MATLAB's deploytool) can be executed.

# MATLAB Runtime
# Run compiled MATLAB applications or components without installing MATLAB
# The MATLAB Runtime is a standalone set of shared libraries that enables the
# execution of compiled MATLAB applications or components. When used together,
# MATLAB, MATLAB Compiler, and the MATLAB Runtime enable you to create and distribute
# numerical applications or software components quickly and securely.
#
# See https://www.mathworks.com/products/compiler/matlab-runtime.html for more info.
#
# @author blacktigerafu & Riccardo De Martis
# @creation 2022-Jul-30
#

FROM ubuntu:22.04
MAINTAINER blacktigerafu<1337456911@qq.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN sed -i s/cn.archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list && \
    apt-get -q update && \
    apt-get install -q -y --no-install-recommends \
      openjdk-8-jdk \
      xorg \
      unzip \
      wget \
      curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# COPY the MCR from MathWorks site an install with -mode silent

COPY ./MATLAB_Runtime_R2021b_Update_3_glnxa64.zip /mcr-install/

RUN mkdir /opt/mcr && \
    cd /mcr-install && \
    unzip -q MATLAB_Runtime_R2021b_Update_3_glnxa64.zip&& \
    rm -f MATLAB_Runtime_R2021b_Update_3_glnxa64.zip&& \
    ./install -destinationFolder /opt/mcr -agreeToLicense yes -mode silent && \
    cd / && \
    rm -rf mcr-install

# Configure environment variables for MCR
ENV LD_LIBRARY_PATH /opt/mcr/v911/runtime/glnxa64:/opt/mcr/v911/bin/glnxa64:/opt/mcr/v911/sys/os/glnxa64:/opt/mcr/v911/extern/bin/glnxa64

ENV XAPPLRESDIR /etc/X11/app-defaults
